service: serverlessguru
# org: riverwalkdevelopers
# app: serverlessguru-test

plugins:
  - serverless-pseudo-parameters
  - serverless-plugin-additional-stacks
  - serverless-iam-roles-per-function
  - serverless-plugin-include-dependencies
  - serverless-appsync-plugin

provider:
  name: aws
  runtime: nodejs12.x
  profile: rwdvs
  region: ${file(./env.yml):${'${self:provider.stage}.REGION'}}
  timeout: ${file(./env.yml):${'${self:provider.stage}.TIMEOUT'}}
  stackName: ${self:service}
  stage: ${opt:stage, 'dev'}

custom:
  base: ${self:service}-${self:provider.stage}

  postTableName: ${self:custom.base}-posts
  userTableName: ${self:custom.base}-users
  lambdaFunctionName: ${self:custom.base}-users

  role:
    arn: ${file(./env.yml):${'${self:provider.stage}.ARN_IAM'}}
    cognito:
      auth:
        name: ${self:custom.base}-auth-CognitoRole
        arn: { Fn::GetAtt: [CognitoAuthRole, Arn] }
      unAuth:
        name: ${self:custom.base}-unAuth-CognitoRole
        arn: { Fn::GetAtt: [CognitoUnauthRole, Arn] }
    dynamodb:
      name: ${self:custom.base}-DynamoDB-AppSyncServiceRole
      arn: ${self:custom.role.arn}/${self:custom.role.dynamodb.name}
    logging:
      name: ${self:custom.base}-Logging-AppSyncServiceRole
      arn: { Fn::GetAtt: [AppSyncLoggingServiceRole, Arn] }
    lambda:
      name: ${self:custom.lambdaFunctionName}
      arn: { Fn::GetAtt: [AppSyncLambdaServiceRole, Arn] }

  additionalStacks:
    cognitoResources:
      Deploy: Before
      StackName: ${self:custom.base}-cognito
      Resources: ${file(./resources/cognito.yml)}
      Outputs: ${file(./resources/cognito-outputs.yml)}
    dynamoDBResources:
      Deploy: Before
      StackName: ${self:custom.base}-dynamodb
      Resources: ${file(./resources/dynamodb.yml)}

  appSync:
    name: ${self:custom.base}-api
    authenticationType: AWS_IAM
    logConfig:
      loggingRoleArn: ${self:custom.role.logging.arn}
      level: ALL
    mappingTemplates:
      - ${file(resolvers/dynamodb.yml)}
      - ${file(resolvers/lambda.yml)}
    serviceRole: "AppSyncServiceRole"
    dataSources:
      - type: AWS_LAMBDA
        name: LambdaDataSource
        description: 'Lambda DataSource'
        config:
          functionName: users
          serviceRoleArn: ${self:custom.role.lambda.arn}
      - type: AMAZON_DYNAMODB
        name: PostDataSource
        description: 'Posts DataSource'
        config:
          tableName: ${self:custom.postTableName}
          serviceRoleArn: ${self:custom.role.dynamodb.arn}
      - type: AMAZON_DYNAMODB
        name: UserDataSource
        description: 'Users DataSource'
        config:
          tableName: ${self:custom.userTableName}
          serviceRoleArn: ${self:custom.role.dynamodb.arn}

functions:
  users:
    handler: handler.users

resources:
  - ${file(resources/logging.yml)}
  - ${file(resources/lambda.yml)}
