UserPool:
  Type: AWS::Cognito::UserPool
  Properties:
    UserPoolName: ${self:custom.base}-userpool
    UsernameAttributes:
      - phone_number
    Schema:
      - Name: name
        AttributeDataType: String
        Mutable: true
        Required: false

UserPoolClient:
  Type: AWS::Cognito::UserPoolClient
  Properties:
    ClientName: ${self:custom.base}-client
    GenerateSecret: false
    UserPoolId:
      Ref: UserPool

IdentityPool:
  Type: AWS::Cognito::IdentityPool
  Properties:
    IdentityPoolName: ${self:custom.base}-identity-pool
    AllowUnauthenticatedIdentities: false
    CognitoIdentityProviders:
      - ClientId:
          Ref: UserPoolClient
        ProviderName:
          Fn::GetAtt: [UserPool, ProviderName]

CognitoAuthRole:
  Type: AWS::IAM::Role
  Properties:
    RoleName: ${self:custom.role.cognito.auth.name}
    Path: /
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: "Allow"
          Principal:
            Federated: "cognito-identity.amazonaws.com"
          Action:
            - "sts:AssumeRoleWithWebIdentity"
          Condition:
            StringEquals:
              "cognito-identity.amazonaws.com:aud":
                Ref: IdentityPool
            # "ForAnyValue:StringLike":
            #   "cognito-identity.amazonaws.com:amr": authenticated
    Policies:
      - PolicyName: ${self:custom.role.cognito.auth.name}-Policy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - "mobileanalytics:PutEvents"
                - "cognito-sync:*"
                - "cognito-identity:*"
              Resource: "*"
            - Effect: "Allow"
              Action:
                - appSync:GraphQL
              Resource: "*"
                # - arn:aws:appsync:#{self:provider.stage}:#{AWS::AccountId}:apis/*/*

CognitoUnauthRole:
  Type: AWS::IAM::Role
  Properties:
    RoleName: ${self:custom.role.cognito.unAuth.name}
    Path: /
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: "Allow"
          Principal:
            Federated: "cognito-identity.amazonaws.com"
          Action:
            - "sts:AssumeRoleWithWebIdentity"
          Condition:
            StringEquals:
              "cognito-identity.amazonaws.com:aud":
                Ref: IdentityPool
            # "ForAnyValue:StringLike":
            #   "cognito-identity.amazonaws.com:amr": unauthenticated
    Policies:
      - PolicyName: ${self:custom.role.cognito.unAuth.name}-Policy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - "mobileanalytics:PutEvents"
                - "cognito-sync:*"
              Resource: "*"
            - Effect: "Allow"
              Action:
                - appSync:GraphQL
              Resource: "*"
                # - arn:aws:appsync:#{AWS::Region}:#{AWS::AccountId}:apis/*/types/Query/fields/getEmployee

IdentityPoolRoles:
  Type: AWS::Cognito::IdentityPoolRoleAttachment
  Properties:
    IdentityPoolId:
      Ref: IdentityPool
    Roles:
      authenticated:
        Fn::GetAtt: [CognitoAuthRole, Arn]
      unauthenticated:
        Fn::GetAtt: [CognitoUnauthRole, Arn]