PostTable:
  Type: 'AWS::DynamoDB::Table'
  Properties:
    KeySchema:
      - 
        AttributeName: id
        KeyType: HASH
    AttributeDefinitions:
      - 
        AttributeName: id
        AttributeType: S
    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1
    TableName: ${file(./env.yml):${'${self:provider.stage}.DYNAMODB.POSTS.NAME'}}

UserTable:
  Type: 'AWS::DynamoDB::Table'
  Properties:
    KeySchema:
      - 
        AttributeName: id
        KeyType: HASH
    AttributeDefinitions:
      - 
        AttributeName: id
        AttributeType: S
    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1
    TableName: ${file(./env.yml):${'${self:provider.stage}.DYNAMODB.USERS.NAME'}}

AppSyncDynamoDBServiceRole:
  Type: "AWS::IAM::Role"
  Properties:
    RoleName: ${file(./env.yml):${'${self:provider.stage}.DYNAMODB.ROLE_NAME'}}
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - 
          Effect: "Allow"
          Principal:
            Service:
              - "appsync.amazonaws.com"
          Action:
            - "sts:AssumeRole"
    Policies:
      - 
        PolicyName: ${file(./env.yml):${'${self:provider.stage}.DYNAMODB.POLICY_NAME'}}
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - 
              Effect: "Allow"
              Action:
                - "dynamodb:Query"
                - "dynamodb:BatchWriteItem"
                - "dynamodb:GetItem"
                - "dynamodb:DeleteItem"
                - "dynamodb:PutItem"
                - "dynamodb:Scan"
                - "dynamodb:UpdateItem"
                - "dynamodb:BatchGetItem"
              Resource: 
                - ${file(./env.yml):${'${self:provider.stage}.DYNAMODB.POSTS.RESOURCE'}}
                - ${file(./env.yml):${'${self:provider.stage}.DYNAMODB.POSTS.RESOURCE'}}/*
                - ${file(./env.yml):${'${self:provider.stage}.DYNAMODB.USERS.RESOURCE'}}
                - ${file(./env.yml):${'${self:provider.stage}.DYNAMODB.USERS.RESOURCE'}}/*

