Resources:
  AppSyncLambdaServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: ${file(./env.yml):${'${self:provider.stage}.LAMBDA.ROLE_NAME'}}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "appsync.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: ${file(./env.yml):${'${self:provider.stage}.LAMBDA.POLICY_NAME'}}
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "lambda:InvokeFunction"
                Resource:
                  - ${file(./env.yml):${'${self:provider.stage}.LAMBDA.RESOURCE'}}
                  - ${file(./env.yml):${'${self:provider.stage}.LAMBDA.RESOURCE'}}/*
