Resources:
  AppSyncLambdaServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "Lambda-${self:custom.appSync.serviceRole}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "appsync.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: "Lambda-${self:custom.appSync.serviceRole}-Policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "lambda:invokeFunction"
                Resource:
                  - "${file(./env.yml):${'${self:provider.stage}.ARN_LAMBDA'}}/${self:custom.lambdaFunctionName}"
                  - "${file(./env.yml):${'${self:provider.stage}.ARN_LAMBDA'}}/${self:custom.lambdaFunctionName}/*"