Resources:
  AppSyncLoggingServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: ${file(./env.yml):${'${self:provider.stage}.LOGGING.ROLE_NAME'}}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "appsync.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: ${file(./env.yml):${'${self:provider.stage}.LOGGING.POLICY_NAME'}}
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"